### ISSUE TITLE
AUR install fails

### ISSUE THREAD

**Issue by lewisde** [odknt/bspwmbar#16]
Not sure if this is your responsibility. v0.4.1.tar.gz fails validity check.

  -> Found config.h
==> Validating source files with sha256sums...
    v0.4.1.tar.gz ... FAILED
    config.h ... Skipped
==> ERROR: One or more files did not pass the validity check!
Error downloading sources: bspwmbar

**Comment by odknt** [comment]
@lewisde Thanks. I fixed PKGBUILD.
