### ISSUE TITLE
Can't start bar

### ISSUE THREAD

**Issue by spookykidmm** [odknt/bspwmbar#17]
I get an error: bspwm_connect(): Failed to connect to the socket
Arch Linux
bspwm: 0.9.7-1
bspwmbar: 0.4.1-2
This is my first time using bspwm, so I could just be being an idiot, please tell me if so!

**Comment by odknt** [comment]
Sorry, bspwmbar was failing to connect to bspwm socket if using default bspwm socket path.

**Comment by mrgreen3** [comment]
Getting same error if running in a terminal, the README only tells you how to build bspwmbar not how to get it running/ configuring. Would be able to help more if I knew how to get it started????

**Comment by mxmilkiib** [comment]
```
$ ls /tmp/bsp*
/tmp/bspwm_1_0-socket
$ bspwmbar
bspwm_connect(): Failed to connect to the socket
bspwmbar_init(): Failed to init bspwmbar
zsh: segmentation fault (core dumped)  bspwmbar
```

**Comment by mxmilkiib** [comment]
Today the socket ends `_0_0` and I get the same error message. I think the change is because before I was running Sway in another PTY.

**Comment by odknt** [comment]
I believe the issue fixed on master.
I was getting bspwm socket path in the wrong way so occurred the issue when `BSPWM_SOCKET` is not set.

**Comment by mxmilkiib** [comment]
Indeed it is, apologies, thanks :)
