### ISSUE TITLE
regular clock support?

### ISSUE THREAD

**Issue by FrostKnight** [odknt/bspwmbar#32]
Is it possible to change the 24 hour clock, to a 12 hour clock in this?
And if not, can you support this feature in future?
If it does, can you document how? 
It is a lovely status bar, minimal and all that, but that is my only issue with it.

**Comment by odknt** [comment]
You can modify datetime format in `config.h`.
Please try replace `%H:%M` with `%I:%M` and rebuild.

**Comment by FrostKnight** [comment]
Thank you, to be fair, I stopped using bspwm for the time being, but this worked for i3's window manager.  Thank you though!
