### ISSUE TITLE
Segfault with nvidia graphic card

### ISSUE THREAD

**Issue by fppn** [odknt/bspwmbar#34]
Starting bspwmbar result in error `segmentation fault (core dumped)` if monitor is attached to Nvidia graphic card.
On the same system everything works fine if I use intel integrated graphic card.

I tried building bspwmbar with default config and with most modules disabled (I left active only system tray on the right and default modules on the left).

I'm using proprietary Nvidia driver on Arch.

**Comment by odknt** [comment]
I using Nvidia graphic card too, but not reproduce.
Maybe there is a problem in config.h.

**Comment by stefanhusmann** [comment]
For me it also segfaults, but I use nouveau. I use the default config.h.

**Comment by Bensatankki** [comment]
Same problem for me, bspwmbar-x11-git from AUR works though

**Comment by odknt** [comment]
Sorry, I'm late. I fixed the problem.
