### ISSUE TITLE
Some icons missing + "feature" facilitation request

### ISSUE THREAD

**Issue by exchaex** [odknt/bspwmbar#41]
Great piece of software!
I installed the font package but some icons are still missing, for example master volume.
[imgur](https://imgur.com/PC99VOul.png)
There were others but I removed them.
Also... Idk if it's useful for others but I need a way to set the poll time globally of for every single module, there should be a line in config.h to allow inexpert users to customize a little more the bar.

**Comment by odknt** [comment]
I fixed example config.
Nerd fonts has been breaking changed about a year ago.

I’m also dissatisfied with the current module design, so when I have time, I plan to make major changes, including other issues.

Alternatively, create a separate project that supports configuration files and dynamic loading of modules.
